name: Install Dependencies
description: This is a composite GitHub Action that sets up Yarn, Node.js, and installs the project's dependencies.

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: yarn

    - name: Install Yarn
      run: |
        npm install -g yarn@4.1.0
      shell: bash

    - name: Install Dependencies with Yarn
      run: |
        yarn install --frozen-lockfile
      shell: bash
