name: Unit Test / Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

#      - name: Lint
#        run: |
#          yarn lint
#          yarn type

#      - name: Test
#        run: |
#          yarn run test --ci
#          yarn test:type

      - name: Bundle watch
        run: |
          yarn bundlewatch
