name: Package Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Manual Checkout
      - uses: actions/checkout@v4

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
